# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sources_api import SourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSourcesApi(unittest.TestCase):
    """SourcesApi unit test stubs"""

    def setUp(self):
        self.api = SourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_source_projects_project_id_adapters_adapter_id_sources_source_id_put(self):
        """Test case for create_source_projects_project_id_adapters_adapter_id_sources_source_id_put

        Create Source  # noqa: E501
        """
        pass

    def test_read_source_projects_project_id_adapters_adapter_id_sources_source_id_get(self):
        """Test case for read_source_projects_project_id_adapters_adapter_id_sources_source_id_get

        Read Source  # noqa: E501
        """
        pass

    def test_read_sources_projects_project_id_adapters_adapter_id_sources_get(self):
        """Test case for read_sources_projects_project_id_adapters_adapter_id_sources_get

        Read Sources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
