# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.adapters_api import AdaptersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAdaptersApi(unittest.TestCase):
    """AdaptersApi unit test stubs"""

    def setUp(self):
        self.api = AdaptersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_adapter_projects_project_id_adapters_put(self):
        """Test case for create_adapter_projects_project_id_adapters_put

        Create Adapter  # noqa: E501
        """
        pass

    def test_delete_adapter_projects_project_id_adapters_adapter_id_delete(self):
        """Test case for delete_adapter_projects_project_id_adapters_adapter_id_delete

        Delete Adapter  # noqa: E501
        """
        pass

    def test_read_adapter_projects_project_id_adapters_adapter_id_get(self):
        """Test case for read_adapter_projects_project_id_adapters_adapter_id_get

        Read Adapter  # noqa: E501
        """
        pass

    def test_read_adapters_projects_project_id_adapters_get(self):
        """Test case for read_adapters_projects_project_id_adapters_get

        Read Adapters  # noqa: E501
        """
        pass

    def test_update_adapter_projects_project_id_adapters_adapter_id_put(self):
        """Test case for update_adapter_projects_project_id_adapters_adapter_id_put

        Update Adapter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
