# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scenario_api import ScenarioApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScenarioApi(unittest.TestCase):
    """ScenarioApi unit test stubs"""

    def setUp(self):
        self.api = ScenarioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_scenario_projects_project_id_adapters_adapter_id_scenario_put(self):
        """Test case for create_scenario_projects_project_id_adapters_adapter_id_scenario_put

        Create Scenario  # noqa: E501
        """
        pass

    def test_read_scenario_projects_project_id_adapters_adapter_id_scenario_get(self):
        """Test case for read_scenario_projects_project_id_adapters_adapter_id_scenario_get

        Read Scenario  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
