# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.response_read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get import ResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet(unittest.TestCase):
    """ResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet(self):
        """Test ResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get.ResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
