# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_api import ProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project_projects_put(self):
        """Test case for create_project_projects_put

        Create Project  # noqa: E501
        """
        pass

    def test_delete_project_projects_project_id_delete(self):
        """Test case for delete_project_projects_project_id_delete

        Delete Project  # noqa: E501
        """
        pass

    def test_load_example_project_load_example_project_get(self):
        """Test case for load_example_project_load_example_project_get

        Load Example Project  # noqa: E501
        """
        pass

    def test_load_example_project_load_optimization_example_get(self):
        """Test case for load_example_project_load_optimization_example_get

        Load Example Project  # noqa: E501
        """
        pass

    def test_read_project_projects_project_id_get(self):
        """Test case for read_project_projects_project_id_get

        Read Project  # noqa: E501
        """
        pass

    def test_read_projects_projects_get(self):
        """Test case for read_projects_projects_get

        Read Projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
