# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.queues_api import QueuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestQueuesApi(unittest.TestCase):
    """QueuesApi unit test stubs"""

    def setUp(self):
        self.api = QueuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_queue_projects_project_id_adapters_adapter_id_queues_queue_id_put(self):
        """Test case for create_queue_projects_project_id_adapters_adapter_id_queues_queue_id_put

        Create Queue  # noqa: E501
        """
        pass

    def test_read_queue_projects_project_id_adapters_adapter_id_queues_queue_id_get(self):
        """Test case for read_queue_projects_project_id_adapters_adapter_id_queues_queue_id_get

        Read Queue  # noqa: E501
        """
        pass

    def test_read_queues_projects_project_id_adapters_adapter_id_queues_get(self):
        """Test case for read_queues_projects_project_id_adapters_adapter_id_queues_get

        Read Queues  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
