# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.any_of_json_adapter_resource_data_items import AnyOfJsonAdapterResourceDataItems  # noqa: E501
from swagger_client.rest import ApiException


class TestAnyOfJsonAdapterResourceDataItems(unittest.TestCase):
    """AnyOfJsonAdapterResourceDataItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfJsonAdapterResourceDataItems(self):
        """Test AnyOfJsonAdapterResourceDataItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.any_of_json_adapter_resource_data_items.AnyOfJsonAdapterResourceDataItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
