# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.processes_api import ProcessesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProcessesApi(unittest.TestCase):
    """ProcessesApi unit test stubs"""

    def setUp(self):
        self.api = ProcessesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_process_projects_project_id_adapters_adapter_id_processes_process_id_put(self):
        """Test case for create_process_projects_project_id_adapters_adapter_id_processes_process_id_put

        Create Process  # noqa: E501
        """
        pass

    def test_read_process_projects_project_id_adapters_adapter_id_processes_process_id_get(self):
        """Test case for read_process_projects_project_id_adapters_adapter_id_processes_process_id_get

        Read Process  # noqa: E501
        """
        pass

    def test_read_processes_projects_project_id_adapters_adapter_id_processes_get(self):
        """Test case for read_processes_projects_project_id_adapters_adapter_id_processes_get

        Read Processes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
