# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.simulation_api import SimulationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSimulationApi(unittest.TestCase):
    """SimulationApi unit test stubs"""

    def setUp(self):
        self.api = SimulationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_run_simulation_projects_project_id_adapters_adapter_id_run_simulation_get(self):
        """Test case for run_simulation_projects_project_id_adapters_adapter_id_run_simulation_get

        Run Simulation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
