# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.materials_api import MaterialsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMaterialsApi(unittest.TestCase):
    """MaterialsApi unit test stubs"""

    def setUp(self):
        self.api = MaterialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_material_projects_project_id_adapters_adapter_id_materials_material_id_put(self):
        """Test case for create_material_projects_project_id_adapters_adapter_id_materials_material_id_put

        Create Material  # noqa: E501
        """
        pass

    def test_read_material_projects_project_id_adapters_adapter_id_materials_material_id_get(self):
        """Test case for read_material_projects_project_id_adapters_adapter_id_materials_material_id_get

        Read Material  # noqa: E501
        """
        pass

    def test_read_materials_projects_project_id_adapters_adapter_id_materials_get(self):
        """Test case for read_materials_projects_project_id_adapters_adapter_id_materials_get

        Read Materials  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
