# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.resources_api import ResourcesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestResourcesApi(unittest.TestCase):
    """ResourcesApi unit test stubs"""

    def setUp(self):
        self.api = ResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put(self):
        """Test case for create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put

        Create Resource  # noqa: E501
        """
        pass

    def test_delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete(self):
        """Test case for delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete

        Delete Resource  # noqa: E501
        """
        pass

    def test_read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get(self):
        """Test case for read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get

        Read Resource  # noqa: E501
        """
        pass

    def test_read_resources_projects_project_id_adapters_adapter_id_resources_get(self):
        """Test case for read_resources_projects_project_id_adapters_adapter_id_resources_get

        Read Resources  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
