# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.optimization_api import OptimizationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOptimizationApi(unittest.TestCase):
    """OptimizationApi unit test stubs"""

    def setUp(self):
        self.api = OptimizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_optimization_pareto_front_projects_project_id_adapters_adapter_id_optimize_configuration_pareto_front_performances_get(self):
        """Test case for get_optimization_pareto_front_projects_project_id_adapters_adapter_id_optimize_configuration_pareto_front_performances_get

        Get Optimization Pareto Front  # noqa: E501
        """
        pass

    def test_get_optimization_results_projects_project_id_adapters_adapter_id_optimize_configuration_results_get(self):
        """Test case for get_optimization_results_projects_project_id_adapters_adapter_id_optimize_configuration_results_get

        Get Optimization Results  # noqa: E501
        """
        pass

    def test_get_optimization_solution_projects_project_id_adapters_adapter_id_optimize_configuration_solution_id_get(self):
        """Test case for get_optimization_solution_projects_project_id_adapters_adapter_id_optimize_configuration_solution_id_get

        Get Optimization Solution  # noqa: E501
        """
        pass

    def test_register_adapter_with_evaluation_projects_project_id_adapters_adapter_id_optimize_configuration_register_solution_id_get(self):
        """Test case for register_adapter_with_evaluation_projects_project_id_adapters_adapter_id_optimize_configuration_register_solution_id_get

        Register Adapter With Evaluation  # noqa: E501
        """
        pass

    def test_run_configuration_optimization_projects_project_id_adapters_adapter_id_optimize_configuration_post(self):
        """Test case for run_configuration_optimization_projects_project_id_adapters_adapter_id_optimize_configuration_post

        Run Configuration Optimization  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
