# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.capability_process_data import CapabilityProcessData  # noqa: E501
from swagger_client.rest import ApiException


class TestCapabilityProcessData(unittest.TestCase):
    """CapabilityProcessData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCapabilityProcessData(self):
        """Test CapabilityProcessData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.capability_process_data.CapabilityProcessData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
