# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SinkData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'description': 'str',
        'location': 'list[float]',
        'material_type': 'str',
        'input_queues': 'list[str]'
    }

    attribute_map = {
        'id': 'ID',
        'description': 'description',
        'location': 'location',
        'material_type': 'material_type',
        'input_queues': 'input_queues'
    }

    def __init__(self, id=None, description=None, location=None, material_type=None, input_queues=None):  # noqa: E501
        """SinkData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._description = None
        self._location = None
        self._material_type = None
        self._input_queues = None
        self.discriminator = None
        self.id = id
        self.description = description
        self.location = location
        self.material_type = material_type
        self.input_queues = input_queues

    @property
    def id(self):
        """Gets the id of this SinkData.  # noqa: E501


        :return: The id of this SinkData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SinkData.


        :param id: The id of this SinkData.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self):
        """Gets the description of this SinkData.  # noqa: E501


        :return: The description of this SinkData.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SinkData.


        :param description: The description of this SinkData.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def location(self):
        """Gets the location of this SinkData.  # noqa: E501


        :return: The location of this SinkData.  # noqa: E501
        :rtype: list[float]
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this SinkData.


        :param location: The location of this SinkData.  # noqa: E501
        :type: list[float]
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def material_type(self):
        """Gets the material_type of this SinkData.  # noqa: E501


        :return: The material_type of this SinkData.  # noqa: E501
        :rtype: str
        """
        return self._material_type

    @material_type.setter
    def material_type(self, material_type):
        """Sets the material_type of this SinkData.


        :param material_type: The material_type of this SinkData.  # noqa: E501
        :type: str
        """
        if material_type is None:
            raise ValueError("Invalid value for `material_type`, must not be `None`")  # noqa: E501

        self._material_type = material_type

    @property
    def input_queues(self):
        """Gets the input_queues of this SinkData.  # noqa: E501


        :return: The input_queues of this SinkData.  # noqa: E501
        :rtype: list[str]
        """
        return self._input_queues

    @input_queues.setter
    def input_queues(self, input_queues):
        """Sets the input_queues of this SinkData.


        :param input_queues: The input_queues of this SinkData.  # noqa: E501
        :type: list[str]
        """
        if input_queues is None:
            raise ValueError("Invalid value for `input_queues`, must not be `None`")  # noqa: E501

        self._input_queues = input_queues

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SinkData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SinkData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
