# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SourceData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'description': 'str',
        'location': 'list[float]',
        'material_type': 'str',
        'time_model_id': 'str',
        'router': 'RouterType',
        'routing_heuristic': 'RoutingHeuristic',
        'output_queues': 'list[str]'
    }

    attribute_map = {
        'id': 'ID',
        'description': 'description',
        'location': 'location',
        'material_type': 'material_type',
        'time_model_id': 'time_model_id',
        'router': 'router',
        'routing_heuristic': 'routing_heuristic',
        'output_queues': 'output_queues'
    }

    def __init__(self, id=None, description=None, location=None, material_type=None, time_model_id=None, router=None, routing_heuristic=None, output_queues=None):  # noqa: E501
        """SourceData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._description = None
        self._location = None
        self._material_type = None
        self._time_model_id = None
        self._router = None
        self._routing_heuristic = None
        self._output_queues = None
        self.discriminator = None
        self.id = id
        self.description = description
        self.location = location
        self.material_type = material_type
        self.time_model_id = time_model_id
        self.router = router
        self.routing_heuristic = routing_heuristic
        self.output_queues = output_queues

    @property
    def id(self):
        """Gets the id of this SourceData.  # noqa: E501


        :return: The id of this SourceData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SourceData.


        :param id: The id of this SourceData.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def description(self):
        """Gets the description of this SourceData.  # noqa: E501


        :return: The description of this SourceData.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SourceData.


        :param description: The description of this SourceData.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def location(self):
        """Gets the location of this SourceData.  # noqa: E501


        :return: The location of this SourceData.  # noqa: E501
        :rtype: list[float]
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this SourceData.


        :param location: The location of this SourceData.  # noqa: E501
        :type: list[float]
        """
        if location is None:
            raise ValueError("Invalid value for `location`, must not be `None`")  # noqa: E501

        self._location = location

    @property
    def material_type(self):
        """Gets the material_type of this SourceData.  # noqa: E501


        :return: The material_type of this SourceData.  # noqa: E501
        :rtype: str
        """
        return self._material_type

    @material_type.setter
    def material_type(self, material_type):
        """Sets the material_type of this SourceData.


        :param material_type: The material_type of this SourceData.  # noqa: E501
        :type: str
        """
        if material_type is None:
            raise ValueError("Invalid value for `material_type`, must not be `None`")  # noqa: E501

        self._material_type = material_type

    @property
    def time_model_id(self):
        """Gets the time_model_id of this SourceData.  # noqa: E501


        :return: The time_model_id of this SourceData.  # noqa: E501
        :rtype: str
        """
        return self._time_model_id

    @time_model_id.setter
    def time_model_id(self, time_model_id):
        """Sets the time_model_id of this SourceData.


        :param time_model_id: The time_model_id of this SourceData.  # noqa: E501
        :type: str
        """
        if time_model_id is None:
            raise ValueError("Invalid value for `time_model_id`, must not be `None`")  # noqa: E501

        self._time_model_id = time_model_id

    @property
    def router(self):
        """Gets the router of this SourceData.  # noqa: E501


        :return: The router of this SourceData.  # noqa: E501
        :rtype: RouterType
        """
        return self._router

    @router.setter
    def router(self, router):
        """Sets the router of this SourceData.


        :param router: The router of this SourceData.  # noqa: E501
        :type: RouterType
        """
        if router is None:
            raise ValueError("Invalid value for `router`, must not be `None`")  # noqa: E501

        self._router = router

    @property
    def routing_heuristic(self):
        """Gets the routing_heuristic of this SourceData.  # noqa: E501


        :return: The routing_heuristic of this SourceData.  # noqa: E501
        :rtype: RoutingHeuristic
        """
        return self._routing_heuristic

    @routing_heuristic.setter
    def routing_heuristic(self, routing_heuristic):
        """Sets the routing_heuristic of this SourceData.


        :param routing_heuristic: The routing_heuristic of this SourceData.  # noqa: E501
        :type: RoutingHeuristic
        """
        if routing_heuristic is None:
            raise ValueError("Invalid value for `routing_heuristic`, must not be `None`")  # noqa: E501

        self._routing_heuristic = routing_heuristic

    @property
    def output_queues(self):
        """Gets the output_queues of this SourceData.  # noqa: E501


        :return: The output_queues of this SourceData.  # noqa: E501
        :rtype: list[str]
        """
        return self._output_queues

    @output_queues.setter
    def output_queues(self, output_queues):
        """Sets the output_queues of this SourceData.


        :param output_queues: The output_queues of this SourceData.  # noqa: E501
        :type: list[str]
        """
        if output_queues is None:
            raise ValueError("Invalid value for `output_queues`, must not be `None`")  # noqa: E501

        self._output_queues = output_queues

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SourceData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourceData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
