# coding: utf-8

"""
    ProdSim API

     The ProdSim-API allows you to create and run production simulations and optimizations with the ProdSim library.    # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: sebastianbehrendt97@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ResourcesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put(self, body, project_id, adapter_id, resource_id, **kwargs):  # noqa: E501
        """Create Resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put(body, project_id, adapter_id, resource_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Resource body: (required)
        :param str project_id: (required)
        :param str adapter_id: (required)
        :param str resource_id: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put_with_http_info(body, project_id, adapter_id, resource_id, **kwargs)  # noqa: E501
        else:
            (data) = self.create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put_with_http_info(body, project_id, adapter_id, resource_id, **kwargs)  # noqa: E501
            return data

    def create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put_with_http_info(self, body, project_id, adapter_id, resource_id, **kwargs):  # noqa: E501
        """Create Resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put_with_http_info(body, project_id, adapter_id, resource_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Resource body: (required)
        :param str project_id: (required)
        :param str adapter_id: (required)
        :param str resource_id: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'project_id', 'adapter_id', 'resource_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put`")  # noqa: E501
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put`")  # noqa: E501
        # verify the required parameter 'adapter_id' is set
        if ('adapter_id' not in params or
                params['adapter_id'] is None):
            raise ValueError("Missing the required parameter `adapter_id` when calling `create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put`")  # noqa: E501
        # verify the required parameter 'resource_id' is set
        if ('resource_id' not in params or
                params['resource_id'] is None):
            raise ValueError("Missing the required parameter `resource_id` when calling `create_resource_projects_project_id_adapters_adapter_id_resources_resource_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'adapter_id' in params:
            path_params['adapter_id'] = params['adapter_id']  # noqa: E501
        if 'resource_id' in params:
            path_params['resource_id'] = params['resource_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/projects/{project_id}/adapters/{adapter_id}/resources/{resource_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete(self, project_id, adapter_id, resource_id, **kwargs):  # noqa: E501
        """Delete Resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete(project_id, adapter_id, resource_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str adapter_id: (required)
        :param str resource_id: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete_with_http_info(project_id, adapter_id, resource_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete_with_http_info(project_id, adapter_id, resource_id, **kwargs)  # noqa: E501
            return data

    def delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete_with_http_info(self, project_id, adapter_id, resource_id, **kwargs):  # noqa: E501
        """Delete Resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete_with_http_info(project_id, adapter_id, resource_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str adapter_id: (required)
        :param str resource_id: (required)
        :return: object
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'adapter_id', 'resource_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete`")  # noqa: E501
        # verify the required parameter 'adapter_id' is set
        if ('adapter_id' not in params or
                params['adapter_id'] is None):
            raise ValueError("Missing the required parameter `adapter_id` when calling `delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete`")  # noqa: E501
        # verify the required parameter 'resource_id' is set
        if ('resource_id' not in params or
                params['resource_id'] is None):
            raise ValueError("Missing the required parameter `resource_id` when calling `delete_resource_projects_project_id_adapters_adapter_id_resources_resource_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'adapter_id' in params:
            path_params['adapter_id'] = params['adapter_id']  # noqa: E501
        if 'resource_id' in params:
            path_params['resource_id'] = params['resource_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/projects/{project_id}/adapters/{adapter_id}/resources/{resource_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='object',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get(self, project_id, adapter_id, resource_id, **kwargs):  # noqa: E501
        """Read Resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get(project_id, adapter_id, resource_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str adapter_id: (required)
        :param str resource_id: (required)
        :return: ResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get_with_http_info(project_id, adapter_id, resource_id, **kwargs)  # noqa: E501
        else:
            (data) = self.read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get_with_http_info(project_id, adapter_id, resource_id, **kwargs)  # noqa: E501
            return data

    def read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get_with_http_info(self, project_id, adapter_id, resource_id, **kwargs):  # noqa: E501
        """Read Resource  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get_with_http_info(project_id, adapter_id, resource_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str adapter_id: (required)
        :param str resource_id: (required)
        :return: ResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'adapter_id', 'resource_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get`")  # noqa: E501
        # verify the required parameter 'adapter_id' is set
        if ('adapter_id' not in params or
                params['adapter_id'] is None):
            raise ValueError("Missing the required parameter `adapter_id` when calling `read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get`")  # noqa: E501
        # verify the required parameter 'resource_id' is set
        if ('resource_id' not in params or
                params['resource_id'] is None):
            raise ValueError("Missing the required parameter `resource_id` when calling `read_resource_projects_project_id_adapters_adapter_id_resources_resource_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'adapter_id' in params:
            path_params['adapter_id'] = params['adapter_id']  # noqa: E501
        if 'resource_id' in params:
            path_params['resource_id'] = params['resource_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/projects/{project_id}/adapters/{adapter_id}/resources/{resource_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ResponseReadResourceProjectsProjectIdAdaptersAdapterIdResourcesResourceIdGet',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def read_resources_projects_project_id_adapters_adapter_id_resources_get(self, project_id, adapter_id, **kwargs):  # noqa: E501
        """Read Resources  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_resources_projects_project_id_adapters_adapter_id_resources_get(project_id, adapter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str adapter_id: (required)
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.read_resources_projects_project_id_adapters_adapter_id_resources_get_with_http_info(project_id, adapter_id, **kwargs)  # noqa: E501
        else:
            (data) = self.read_resources_projects_project_id_adapters_adapter_id_resources_get_with_http_info(project_id, adapter_id, **kwargs)  # noqa: E501
            return data

    def read_resources_projects_project_id_adapters_adapter_id_resources_get_with_http_info(self, project_id, adapter_id, **kwargs):  # noqa: E501
        """Read Resources  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.read_resources_projects_project_id_adapters_adapter_id_resources_get_with_http_info(project_id, adapter_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str adapter_id: (required)
        :return: list[object]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'adapter_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method read_resources_projects_project_id_adapters_adapter_id_resources_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `read_resources_projects_project_id_adapters_adapter_id_resources_get`")  # noqa: E501
        # verify the required parameter 'adapter_id' is set
        if ('adapter_id' not in params or
                params['adapter_id'] is None):
            raise ValueError("Missing the required parameter `adapter_id` when calling `read_resources_projects_project_id_adapters_adapter_id_resources_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['project_id'] = params['project_id']  # noqa: E501
        if 'adapter_id' in params:
            path_params['adapter_id'] = params['adapter_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/projects/{project_id}/adapters/{adapter_id}/resources', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[object]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
